setup eslint,prettier and added max line and one component per file rules along with recommended rules
palaklive/react-quality-assurance pull request #5
Opened 2023-08-07 13:06 UTC by raj-vc

Setup the **EsLint** , **Prettier** along with typescript.
- Added the various **dev Dependencies** which is required in next.js project for linting.
- Created the **setting.json** file for the formatting when file is saved or code in paste.
- Created the **.gitattributes** file to tell git to use **CRLF** for line endings in windows and unix system.
- Created **.prettierrc.json** file to added rules for the formatting the code

 Rules that are covered in **.eslintrc.json**

- Added the recommendation rule in extends from the eslint, prettier, typescript and jsx-ally.
- added the **max-lines** rule for limit 250 which ignore comments and blank lines
- added the no **no-multi-comp** rule to restrict user from creating multiple component in one file
- along with it updated other rule for hooks dependencies , prop types, unused variables.

2023-08-10 04:41 UTC, palaklive commented
Hello @raj-vc 
We have forced the developer to use `LF` as line endings.

2023-08-10 05:45 UTC, palaklive requested changes

2023-08-10 05:45 UTC, palaklive commented on .gitattributes
> +* text=auto eol=crlf
Please update this to Linux styled.

2023-08-10 05:45 UTC, palaklive commented on .prettierignore
> +.next
You can actually pass a flag to your prettier command --ignore-path and then give it the path of your. gitignore file so it will use that instead of the .prettierignore file.

2023-08-10 05:45 UTC, palaklive commented on .prettierrc.json
> +  "endOfLine": "crlf"
enforce lf

2023-08-10 06:18 UTC, raj-vc commented on .eslintrc.json
> +    "react/react-in-jsx-scope": "off",
@palaklive 

So we can directly write component `export default function About() {
  return <h1>About Us</h1>;
}` and use `import React from 'react';` where required

2023-08-10 06:36 UTC, raj-vc commented on .eslintrc.json
> +    "jsx-a11y/anchor-is-valid": "off",
Yes @palaklive

2023-08-11 18:24 UTC, palaklive requested changes

2023-08-11 18:24 UTC, palaklive commented on package.json
> +  "lint-staged": {
try to manage the lint-stage outside the `package.json`

2023-08-11 18:24 UTC, palaklive commented on package.json
> +    "precommit": "lint-staged"
try to keep it with the `.husky` directory to avoid additional script

2023-08-16 07:02 UTC, raj-vc commented on package.json
> +  "lint-staged": {
@palaklive  removed the lint-staged config and added the .lintstagedrc.json file to manage it

2023-08-16 07:03 UTC, raj-vc commented on package.json
> +    "precommit": "lint-staged"
@palaklive  removed the unrequired scripts

2023-08-16 07:04 UTC, raj-vc commented
Added the additional rules for the strict null check along with optional chaining operator (?.) and coalescing operator (??)

2023-08-16 09:37 UTC, palaklive requested changes

2023-08-16 09:37 UTC, palaklive commented on package.json
> +    "typescript": "^5.1.6"
@raj-vc keep it as dev dependency.

2023-08-16 10:45 UTC, raj-vc commented on package.json
> +    "typescript": "^5.1.6"
Sure

2023-08-16 10:46 UTC, raj-vc commented
@palaklive  added the promises rules and organize imports settings

2023-08-16 10:54 UTC, palaklive approved these changes

2023-08-16 10:55 UTC, merged